services:
  front:
    build:
      context: ./front
      args:
        NEXT_PUBLIC_WS_URL: ws://localhost:8080
        NEXT_PUBLIC_REST_URL: http://localhost:8080
    container_name: psychosom-front
    ports:
      - '3000:3000'
    environment:
      - NEXTAUTH_SECRET=24230c0d373a2bba872b0893dc81ec00
      - NEXTAUTH_URL=http://localhost:3000
      - BACKEND_URL=http://back:8080
    depends_on:
      - back

  back:
    build: ./back
    container_name: psychosom-back
    ports:
      - '8080:8080'
    environment:
      - TZ=Europe/Moscow
      - DB_HOST=db
      - DB_NAME=psychosom
      - DB_PORT=5432
      - POSTGRES_USER=psychosom
      - POSTGRES_PASSWORD=psychosom_1234
      - PSYСHOSOM_WEB_URL=http://localhost:3000
      - PSYСHOSOM_BOT_TOKEN=7849359674:AAGu7dC2hjt6JwchT6UIqjt64XHat5UrUH8
      - PSYСHOSOM_BOT_USERNAME=psyhosom_test_1_bot
      - S3_INTERNAL_ENDPOINT=http://s3:9000
      - S3_PUBLIC_ENDPOINT=http://localhost:9000
      - S3_ACCESS_KEY=psychosom
      - S3_SECRET_KEY=psychosom_1234
      - S3_BUCKET=psychosom
      - S3_REGION=eu-north-1
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
      s3-bucket-creator:
        condition: service_completed_successfully

  db:
    image: postgres:15
    container_name: psychosom-db
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "psychosom" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: psychosom
      POSTGRES_USER: psychosom
      POSTGRES_PASSWORD: psychosom_1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3:
    image: minio/minio:latest
    container_name: psychosom-s3
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # Web UI
    environment:
      MINIO_ROOT_USER: psychosom
      MINIO_ROOT_PASSWORD: psychosom_1234
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1" ]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - minio_data:/data

  s3-bucket-creator:
    image: minio/mc:latest
    container_name: psychosom-s3-bucket-creator
    entrypoint: >
      /bin/sh -c "
        mc alias set psychosom_s3 http://s3:9000 psychosom psychosom_1234;
        mc mb -p psychosom_s3/psychosom;
        mc anonymous set download psychosom_s3/psychosom
      "
    depends_on:
      s3:
        condition: service_healthy

networks:
  default:
    name: psychosom

volumes:
  postgres_data:
  minio_data:
