spring:
  application:
    name: psyhosom

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:psyhosom}
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true

  flyway:
    locations: classpath:db/migration
    clean-disabled: false
  sql:
    init:
      mode: never

security:
  jwt:
    private-key-path: classpath:jwt/rsa/private_key.pem
    public-key-path: classpath:jwt/rsa/public_key.pem

telegram:
  bot:
    endpoints:
      confirmation: https://t.me/${PSYHOSOM_BOT_USERNAME:psyhosom_test_2_bot}?start=
    token: ${PSYHOSOM_BOT_TOKEN:8199547612:AAHOhfzIyITbm6XYe_3Wr4rUcVqC867c-C4}
    username: ${PSYHOSOM_BOT_USERNAME:psyhosom_test_2_bot}

frontend:
  url: ${PSYHOSOM_WEB_URL:http://localhost:3000}

springdoc:
  swagger-ui:
    tags-sorter: alpha
