spring:
  application:
    name: psychosom

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:psychosom}
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true
  flyway:
    locations: classpath:db/migration
    clean-disabled: false
  sql:
    init:
      mode: never

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

telegram:
  bot:
    endpoints:
      confirmation: https://t.me/${PSYСHOSOM_BOT_USERNAME:psyhosom_test_2_bot}?start=
    token: ${PSYСHOSOM_BOT_TOKEN:8199547612:AAHOhfzIyITbm6XYe_3Wr4rUcVqC867c-C4}
    username: ${PSYСHOSOM_BOT_USERNAME:psyhosom_test_2_bot}

s3:
  internal-endpoint: ${S3_INTERNAL_ENDPOINT:http://localhost:9000}
  public-endpoint: ${S3_PUBLIC_ENDPOINT:http://localhost:9000}
  region: ${S3_REGION:us-east-1}
  bucket: ${S3_BUCKET:psychosom}
  access-key: ${S3_ACCESS_KEY:psychosom}
  secret-key: ${S3_SECRET_KEY:psychosom_1234}
  path-style-access: true

frontend:
  url: ${PSYCHOSOM_WEB_URL:http://localhost:3000}

security:
  jwt:
    private-key-path: classpath:jwt/rsa/private_key.pem
    public-key-path: classpath:jwt/rsa/public_key.pem

scheduled:
  account-cleaner:
    fixed-rate-ms: 60000
  consultations-notifier:
    fixed-rate-ms: 60000
  ended-consultation-informer:
    fixed-rate-ms: 60000
  psychologist-schedule-slots-addition:
    cron: "0 0 3 * * *"

springdoc:
  swagger-ui:
    tags-sorter: alpha
