spring:
  application:
    name: psyhosom

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/psyhosom
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true

  flyway:
    locations: classpath:db/migration
    clean-disabled: false
  sql:
    init:
      mode: never

security:
  jwt:
    private-key-path: classpath:jwt/rsa/private_key.pem
    public-key-path: classpath:jwt/rsa/public_key.pem

frontend:
  url: ${PSYHOSOM_WEB_URL:http://localhost:3000}
