CREATE TABLE IF NOT EXISTS account
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255) NOT NULL,
    role              VARCHAR(50)  NOT NULL,
    is_confirmed      BOOLEAN      NOT NULL,
    tg_bot_token      VARCHAR(24)  NOT NULL UNIQUE,
    tg_chat_id        BIGINT,
    registration_dttm TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS patient_profile
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT REFERENCES account (id) NOT NULL UNIQUE,
    first_name VARCHAR(255)                   NOT NULL,
    last_name  VARCHAR(255)                   NOT NULL
);

CREATE TABLE IF NOT EXISTS psychologist_profile
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id        BIGINT REFERENCES account (id) NOT NULL UNIQUE,
    first_name        VARCHAR(255)                   NOT NULL,
    last_name         VARCHAR(255)                   NOT NULL,
    article JSONB NOT NULL,
    profile_image_url VARCHAR(255)                   NOT NULL
);

CREATE TABLE IF NOT EXISTS psychologist_education
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    psychologist_id BIGINT REFERENCES psychologist_profile (id) NOT NULL
);

CREATE TABLE IF NOT EXISTS psychologist_education_file
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_id BIGINT REFERENCES psychologist_education (id) NOT NULL,
    file_url     VARCHAR(255)                                  NOT NULL
);

CREATE TABLE IF NOT EXISTS consultation
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    psychologist_id     BIGINT REFERENCES psychologist_profile (id) NOT NULL,
    patient_id          BIGINT REFERENCES patient_profile (id)      NOT NULL,
    status              VARCHAR(50)                                 NOT NULL,
    problem_description VARCHAR(4000),
    start_dttm          TIMESTAMP                                   NOT NULL,
    end_dttm            TIMESTAMP                                   NOT NULL,
    order_dttm          TIMESTAMP                                   NOT NULL,
    confirmation_dttm   TIMESTAMP,
    meeting_link        VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS review
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    psychologist_id BIGINT REFERENCES psychologist_profile (id) NOT NULL,
    patient_id      BIGINT REFERENCES patient_profile (id)      NOT NULL,
    rating          INT                                         NOT NULL,
    text            VARCHAR(2000)                               NOT NULL,
    date            TIMESTAMP
);
