CREATE TABLE IF NOT EXISTS account
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255) NOT NULL,
    role              VARCHAR(50)  NOT NULL,
    is_confirmed      BOOLEAN      NOT NULL,
    tg_bot_token      VARCHAR(24)  NOT NULL UNIQUE,
    tg_chat_id        BIGINT,
    registration_dttm TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS profile
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id        BIGINT REFERENCES account (id) NOT NULL UNIQUE,
    first_name        VARCHAR(255),
    last_name         VARCHAR(255),
    phone_number      VARCHAR(12),
    telegram_username VARCHAR(33)
);
